name: zetci
version: "0.1"
author: Patrik Lindstrom. <patrik.lindstrom.dev>
about: Extracts data from several textfile with set based logic
args:
  - files:
      long: files
      short: f
      takes_value: true
      multiple: true
      min_values: 1
      global: true
  - config:
      short: c
      long: config
      value_name: CONF
      help: Sets a custom config file
      takes_value: true
      global: true
  - output:
      short: o
      long: output
      required: false
      takes_value: true
      global: true
  - verbose:
      short: v
      multiple: true
      help: Sets the level of verbosity
      global: true
  - debug:
      short: d
      long: debug
      help: Enables debug mode
  - quiet:
      short: q
      help: Suppresses all output
      global: true
subcommands:
  - UNION:
      long: union
      short: u
      help: Takes the unique rows of two or more files.
  - INTERSECT:
      long: intersect
      short: i
      help: Gets the rows that exist in all of the files.
  - LEFT:
      long: left
      short: l
      help: Gets the rows that exist in the first file and also in the second file and so on.
  - DIFFERENCE:
      long: difference
      short: d
      help: Gets the rows that do not exist in the first file and but in the second file and so on.