use clap::{Arg, Command};

pub fn cli() -> Command {

    Command::new("set_operations")
        .version("0.1.1")
        .author("Patrik Lindström <patrik.lindstrom@lcube.se>")
        .about("Performs set operations on csv files")
        .arg(Arg::new("output")
            .short('o')
            .long("output")
            .value_name("outfile")
            .help("Sets an output file, stdout if not present")
            .global(true))
        .arg(Arg::new("files")
            .short('f')
            .long("files")
            .value_name("file")
            .help("Sets the input files to use")
            .required(false)
            .value_delimiter(',')
            .global(true))
        .subcommand(Command::new("union")
            .about("Performs union operation on csv files")
            .version("1.0")
            .author("Patrik Lindström <patrik.lindstrom@lcube.se>"))
        .subcommand(Command::new("intersect")
            .about("Performs intersection operation on csv files")
            .version("1.0")
            .author("Patrik Lindström <patrik.lindstrom@lcube.se>"))
        .subcommand(Command::new("diffa")
            .about("Performs difference operation on csv files")
            .version("1.0")
            .author("Patrik Lindström <patrik.lindstrom@lcube.se>"))
        .subcommand(Command::new("xor")
            .about("Performs an -exclusive or- operation on csv files")
            .version("1.0")
            .author("Patrik Lindström <patrik.lindstrom@lcube.se>"))
        .subcommand(Command::new("about")
            .about("Displays the logo")
            .version("1.0")
            .author("Patrik Lindström <patrik.lindstrom@lcube.se>"))
}