use clap::{Arg, Command};

pub fn cli() -> Command {

    Command::new("set_operations")
        .version("1.0")
        .author("Patrik Lindström <patrik.lindstrom@lcube.se>")
        .about("Performs set operations on csv files")
        .arg(Arg::new("OUTPUT")
            .short('o')
            .long("output")
            .value_name("FILE")
            .help("Sets an output file, stdout if not present"))
        .arg(Arg::new("files")
            .short('f')
            .long("files")
            .value_name("FILE")
            .help("Sets the input file to use")
            .required(false))
        .subcommand(Command::new("UNION")
            .about("Performs union operation on csv files")
            .version("1.0")
            .author("Patrik Lindström <patrik.lindstrom@lcube.se>"))
        .subcommand(Command::new("INTERSECT")
            .about("Performs intersection operation on csv files")
            .version("1.0")
            .author("Patrik Lindström <patrik.lindstrom@lcube.se>"))
        .subcommand(Command::new("DIFFERENCE")
            .about("Performs difference operation on csv files")
            .version("1.0")
            .author("Patrik Lindström <patrik.lindstrom@lcube.se>"))
        .subcommand(Command::new("ABOUT")
            .about("Displays the logo")
            .version("1.0")
            .author("Patrik Lindström <patrik.lindstrom@lcube.se>"))
}